### ISSUE TITLE
Pokemon images

### ISSUE THREAD

**Issue by timobrembeck** [PokemonGoers/PokeMap-2#10]
fetch images for all Pokemon, e.g.
- small resolution images with transparent background (and maybe gif-animation) for map markers
- medium resolution for additional information (Sidebar?)

**Comment by sacdallago** [comment]
Remember to have these in CC0 or to make sure that you cite the sources, if the license tells you to do so

**Comment by egazetic1** [comment]
Also the images need to have the same height and width :) For the sidebar at least, otherwise the circle on the picture isn't a circle anymore and it looks weird

**Comment by timobrembeck** [comment]
Right. Faris, I assigned you because I thought you could use your basic-data-script to fetch the images.
[This](http://www.techinsider.io/every-pokemon-in-pokemon-go-full-list-2016-7) source already fits for the sidebar images and we can just resize them if we don't find other icons for the markers.

**Comment by farisca** [comment]
Solution: Fetch the image from PokeData API
