### ISSUE TITLE
PokeMob

### ISSUE THREAD

**Issue by farisca** [PokemonGoers/PokeMap-2#12]
Show PokeMobs warning on the map.

PokeMobs are events where a large group of people forms in a certain location due to the appearance of a rare pokemon. [Here](https://www.youtube.com/watch?v=MLdWbwQJWI0) is an example for a PokeMob.

**Comment by timobrembeck** [comment]
@PokemonGoers/hashpokemongo how will your PokeMobs-alerts be implemented?

**Comment by farisca** [comment]
Duplicated issue: see https://github.com/PokemonGoers/PokeMap-2/issues/32
