### ISSUE TITLE
Dummy Data 

### ISSUE THREAD

**Issue by farisca** [PokemonGoers/PokeMap-2#2]
Figure out what kind of data we get from group A and create a dummy data set.

**Comment by sacdallago** [comment]
From experience I can tell you: come up with a definition yourself and then help A to standardize their data to your needs.

A good starting point is:

``` javascript
{
  pokemon: "pokemon_name"*,
  lat: 43.4444,
  lng: 23.4454,
  createdAt: Date
}
```

\* This is probably the trickiest part! Don't use id's, but rather full names (making sure they are unique) and build up a consistent [slug](http://patterns.dataincubator.org/book/url-slug.html)
