### ISSUE TITLE
Live-twitter UI

### ISSUE THREAD

**Issue by egazetic1** [PokemonGoers/PokeMap-2#23]
"if a user wants to see the live streaming of tweets and the formation of pokeMobs, he/she will be given a UI element on the website that allows for the streaming listener to start."

Which means that we probably need a menu(toolbar) which will have some options for live streaming of tweets. 
- HashPokemongo team will send us information about the tweets and we "just" need to show them on UI. I guess that will also be some API, to which we will make requests every 30 seconds?

**Comment by sacdallago** [comment]
@MajorBreakfast might want jump in here

@egazetic1 yes, you need a function that spawns the desired effect, but don't put too much work into the UI, the guys from @PokemonGoers/catch-em-all said they'd like to take care of that :)

Try to separate as much as possible the map from the actions (inputs) of the user, providing an interface that the guys from the web-site project can overwrite or use but by defining their own UI components :)

**Comment by sacdallago** [comment]
Ah, for your last point: Not an API per-sè, it's part of Twitter's stream API, which you most likely will have to incorporate in your component.
The idea is that when a user _wants_, he/she will start listening to a live twitter feed and the map will show these tweets (or, well, the information that they contain) on the map. For this to work there also needs to be a direct communication between the user and the server where the map will be implemented. I mean: if in general an API is the client that request a thing and the server that will answer with something once, in this case it's the client that asks the server to constantly push new information back. https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications

**Comment by timobrembeck** [comment]
not relevant for the map project anymore
