### ISSUE TITLE
slide bar changes moves the map

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/PokeMap-2#27]
Slide bar change events are also read as mouse events that navigate the map.

**Comment by egazetic1** [comment]
The solution needs some other  parts for the bug to disappear completely:
- It needs to be fixed for IE :) 
  I added an event handler for the mouse.
  In IE it disables dragging after mouse press is released. While in chrome/firefox it disables dragging after mouse press. So IE like usual needs special care.
- Also if the map is used on touch devices, it won't be a mouse anymore, but a touch.  These event handlers are also needed.

I will do these later.

**Comment by sacdallago** [comment]
@egazetic1 first try to discuss with @PokemonGoers/catch-em-all if putting so much effort in this UI element is necessary. Maybe the guys from the website will outsource this to their competences?

**Comment by egazetic1** [comment]
We won't change the UI anymore :) Everything is fixed now. Just wanted that it looks normal on all browsers when we test it.

**Comment by gyachdav** [comment]
Due date to resolve this issue? hint: "later" is not a due date 😄

**Comment by farisca** [comment]
As indicated in the comment https://github.com/PokemonGoers/Catch-em-all/issues/24#issuecomment-245904515 Catch-em-all team will take care of this UI element

**Comment by egazetic1** [comment]
Since we aren't responsible for the slider anymore :) I will close this issue
