### ISSUE TITLE
First draft: Enable a resolution of a route to pokemon

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/PokeMap-2#34]
- [x] When a predicted pokemon is selected on the an option to chart a route on how to get to that pokemon should be enabled. If OSM supports this then use its API to calculate and render a route on the map that will show the user direction on how to get to the pokemon. 
- [x] if we decide to have a location based ad network integrated into the map then the route to the pokemon will be sent to this service provider and appropriate ads will appear along the route. Ads will be placed in a designated div created by @PokemonGoers/catch-em-all.
- [ ] Furthermore if there is a way to enable notifications for the spawn event that happens in the future then the notification will state something like: "Time to go hunt <bulbasaur> it will spawn on 20:34 at these coordinates: <lat,lon|cell>".   Clicking the notification will open the map and will chart a route that leads to the predicted location of the pokemon.

**Comment by timobrembeck** [comment]
What abut the last task: is it still relevant?
If yes, @PokemonGoers/catch-em-all should probably take care of the notification system...

**Comment by timobrembeck** [comment]
As nobody reacted, I assume it isn't relevant anymore.
