### ISSUE TITLE
Change package.json

### ISSUE THREAD

**Issue by farisca** [PokemonGoers/PokeMap-2#41]
Package.json should be modified:
1. change "main" to pokemap.js and make corresponding changes in Makefile, index.html
2. move "devDependencies" to "dependencies"

**Comment by johartl** [comment]
I agree with moving devDependencies to dependencies but what's the reason for changing the `main` key to `pokemap.js` in the package.json?
After running `npm install` (and thus the `postinstall` hook) browserify will generate the `pokemap.bundle.js` which contains everything we need. So shouldn't this be the `main` entry point?
