### ISSUE TITLE
Iteratec logo

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/PokeMap-2#48]
Hey guys,

as in https://github.com/PokemonGoers/Catch-em-all/issues/118 , please hard code the logo in the map at (48.055150, 11.60758)

**Comment by sacdallago** [comment]
Update: I think it makes sense to actually put the logo of Iteratec on all locations with their offices, the lat, lng provided before were only for Munich. The additional locations are:
- Nordstrasse 9 CH- 8006 Zürich
- Mooslackengasse 17 A- 1190 Wien
- Zettachring 10 70567 Stuttgart
- Am Sandtorkai 73 20457 Hamburg
- Berliner Straße 76 63065 Offenbach a. M.
- Königsallee 14 40212 Düsseldorf

You can reverse geo-code via http://www.latlong.net/convert-address-to-lat-long.html

**Comment by farisca** [comment]
Should not be implemented as discussed in https://github.com/PokemonGoers/Catch-em-all/issues/134#issuecomment-255986006
