### ISSUE TITLE
Static Pokémon database

### ISSUE THREAD

**Issue by timobrembeck** [PokemonGoers/PokeMap-2#5]
Create a static database with information about all Pokémon, with e.g.
- Name
- Type
- Species
- Height
- Weight
- Abilities
- Information about training
- Information about breeding
- Information about evolution
- ...

and decide which information is necessary to show on the map and which is not.

**Comment by farisca** [comment]
What kind of db should be used here?

**Comment by farisca** [comment]
OR should we fetch this data at run-time from the internet - e.g. from https://pokemon.gameinfo.io/

**Comment by farisca** [comment]
does this second approach introduce a lot of unnecessary over-heads?

on the other hand, what if they introduce additional pokemons into the game?

**Comment by sacdallago** [comment]
In my opinion: just load data from a file for now. Some mock data, I mean.

Then use data from project A

**Comment by goldbergtatyana** [comment]
yes, as @sacdallago said just use a file now and do not care about pokemons that can potentially be added in the future.
