### ISSUE TITLE
Visualize Pokémon information

### ISSUE THREAD

**Issue by timobrembeck** [PokemonGoers/PokeMap-2#6]
Show additional information to each Pokémon on the map when clicking on it, e.g. as Popup or Sidebar

**Comment by sacdallago** [comment]
Also: Popup click or popup Hoover?

Leaflet has pop-ups built in ;) so it's gonna be ez.

Oh! Did u know: uou can give markers a different icon :P maybe find pngs for every Pokémon?

**Comment by egazetic1** [comment]
Maybe some small informations as a popup Hoover, and then if someone wants more information then we can also add a Popup click :) And then for even more information a sidebar.

**Comment by WoH** [comment]
Hey guys, I'm from Project E and since this will probably be done working with us, I hope you don't mind if I add myself to your conversation here

**Comment by sacdallago** [comment]
@WoH you can watch the repository (top right corner) then you get all the notifications as well :)

**Comment by timobrembeck** [comment]
@WoH we already implemented popups and a simple sidebar for this (see [demo](https://pokemongoers.github.io/PokeMap-2/)).
Of course we will adjust it to your needs.

**Comment by farisca** [comment]
Should this issue be closed? Both popup and sidebar have been implemented

**Comment by sacdallago** [comment]
For me yeah
