### ISSUE TITLE
Most likely pokemon next to user 

### ISSUE THREAD

**Issue by timobrembeck** [PokemonGoers/PokeMap-2#7]
Get the GeoLocation of the user via web and calculate the most likely Pokémon next to user.
Somehow we have to decide what is a reasonable relation between distance and probability to appear, respectively if it is better to recommend an unlikely but very near Pokémon or one which is very likely but far away.

**Comment by goldbergtatyana** [comment]
We will visualize ALL predicted Pokemons (independent of probability to appear). I imagine this to be shown such that predicted Pokemons are first shown within a certain radius away from the user. When the user zoomes out in the map, the more Pokemons are shown. Other suggestions are welcome :)

**Comment by sacdallago** [comment]
@goldbergtatyana what about zoom level inversely proprotional to prediction score?

**Comment by goldbergtatyana** [comment]
I would really show all pokemons together with a probability of their appearance.
