### ISSUE TITLE
Filter by time range

### ISSUE THREAD

**Issue by timobrembeck** [PokemonGoers/PokeMap-2#8]
Add a possibility to filter the map by a time range (i.e predicted to appear in the next day)

**Comment by sacdallago** [comment]
Also in the past!
In the direction of seen between x and y

**Comment by timobrembeck** [comment]
So do we have to show **actual** Pokémon (provided by Group A) or **predicted** Pokémon (provided by Group B) in the past? Just in case there are small deviations ;)

**Comment by sacdallago** [comment]
Actual by A for the past, predicted by B for right now/the future
