### ISSUE TITLE
Style in the topic name

### ISSUE THREAD

**Issue by farisca** [PokemonGoers/PokeMap-2#9]
What does "style" in our topic "Web development basics: DOM, DOM manipulation, styles" refer to? Map style, or pokemon info pop-ups style?

**Comment by sacdallago** [comment]
Topics and project are unbound.

It means style in web pages aka CSS+JS to manipulate the styes

**Comment by gyachdav** [comment]
The topic 

> Web development basics: DOM, DOM manipulation, styles
> 
> Is the topic you will be researching and presenting to the class during presentation week. 

The topic has nothing to do with your project (well not directly).
